import jsPDF from 'jspdf';

export const generateProcedurePDF = (procedure) => {
  try {
    // Create new PDF document
    const pdf = new jsPDF();
    let yPosition = 20;
    const pageWidth = pdf.internal.pageSize.width;
    const margin = 20;
    const contentWidth = pageWidth - (margin * 2);

    // Helper function to add text with word wrapping
    const addText = (text, fontSize = 12, isBold = false, color = [0, 0, 0]) => {
      pdf.setFontSize(fontSize);
      pdf.setTextColor(color[0], color[1], color[2]);
      
      if (isBold) {
        pdf.setFont(undefined, 'bold');
      } else {
        pdf.setFont(undefined, 'normal');
      }

      const lines = pdf.splitTextToSize(text, contentWidth);
      
      // Check if we need a new page
      if (yPosition + (lines.length * fontSize * 0.5) > pdf.internal.pageSize.height - 20) {
        pdf.addPage();
        yPosition = 20;
      }
      
      pdf.text(lines, margin, yPosition);
      yPosition += lines.length * fontSize * 0.5 + 5;
    };

    // Helper function to add a section
    const addSection = (title, items, isWarning = false) => {
      const titleColor = isWarning ? [220, 38, 38] : [37, 99, 235]; // Red for warnings, blue for others
      addText(title, 14, true, titleColor);
      yPosition += 5;
      
      items.forEach((item, index) => {
        const bullet = isWarning ? '⚠️' : '•';
        addText(`${bullet} ${item}`, 11);
      });
      yPosition += 10;
    };

    // Header with company branding
    addText('DentalRescueBot', 18, true, [37, 99, 235]);
    addText('Post-Operative Care Guide', 16, true, [75, 85, 99]);
    yPosition += 10;

    // Procedure title and details
    addText(procedure.name, 16, true, [31, 41, 55]);
    addText(`Specialty: ${procedure.specialtyName}`, 12, false, [107, 114, 126]);
    addText(`Recovery Duration: ${procedure.duration}`, 12, false, [107, 114, 126]);
    yPosition += 15;

    // Overview
    addText('Overview', 14, true, [37, 99, 235]);
    addText(procedure.overview, 11);
    yPosition += 15;

    // Emergency notice
    addText('⚠️ EMERGENCY NOTICE', 12, true, [220, 38, 38]);
    addText('If you experience severe bleeding, difficulty breathing, or signs of severe allergic reaction, call 911 immediately.', 11, false, [153, 27, 27]);
    yPosition += 15;

    // Immediate Aftercare
    addSection('Immediate Aftercare Instructions', procedure.immediateAftercare);

    // Diet Restrictions
    addSection('Diet Restrictions', procedure.dietRestrictions);

    // Warning Signs (highlighted in red)
    addSection('⚠️ Warning Signs - Call Your Dentist Immediately', procedure.warningSignsToCallDoctor, true);

    // Recovery Timeline
    addText('Recovery Timeline', 14, true, [37, 99, 235]);
    yPosition += 5;
    procedure.recoveryTimeline.forEach((timeline) => {
      addText(`Day ${timeline.day}: ${timeline.activity}`, 11);
    });
    yPosition += 15;

    // Medications
    addSection('Medications', procedure.medications);

    // Contact Information
    addText('Need Help?', 14, true, [37, 99, 235]);
    addText('Office Hours: Contact your dental office during regular business hours', 11);
    addText('After Hours: Follow your dentist\'s emergency contact instructions', 11);
    yPosition += 15;

    // Footer
    if (yPosition > pdf.internal.pageSize.height - 40) {
      pdf.addPage();
      yPosition = 20;
    }
    
    yPosition = pdf.internal.pageSize.height - 30;
    pdf.setFontSize(8);
    pdf.setTextColor(107, 114, 126);
    pdf.text('Generated by DentalRescueBot - www.theoncallbot.com', margin, yPosition);
    pdf.text(`Copyright © The OnCall Bot LLC 2025`, margin, yPosition + 10);
    pdf.text(`Generated on: ${new Date().toLocaleDateString()}`, margin, yPosition + 20);

    // Save the PDF
    const fileName = `${procedure.name.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_post_op_guide.pdf`;
    pdf.save(fileName);
    
    return true;
  } catch (error) {
    console.error('Error generating PDF:', error);
    return false;
  }
};

// NEW: Generate branded PDF for assigned patient procedures
export const generateBrandedPatientPDF = async (assignment, procedure, patient, practice) => {
  try {
    const pdf = new jsPDF();
    const pageWidth = pdf.internal.pageSize.width;
    const pageHeight = pdf.internal.pageSize.height;
    const leftMargin = 30;
    const rightMargin = 30;
    const topMargin = 30;
    const bottomMargin = 40;
    const contentWidth = pageWidth - leftMargin - rightMargin;
    let yPosition = topMargin;
    let currentPage = 1;

    // Helper function to convert hex color to RGB
    const hexToRgb = (hex) => {
      const result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex);
      return result ? [
        parseInt(result[1], 16),
        parseInt(result[2], 16),
        parseInt(result[3], 16)
      ] : [0, 51, 102]; // Professional dark blue
    };

    // Get practice brand colors
    const primaryColor = practice.branding?.primaryColor ? 
      hexToRgb(practice.branding.primaryColor) : [0, 51, 102];

    // Helper function to add practice logo
    const addLogo = async () => {
      if (practice.branding?.logo) {
        try {
          // If logo is a data URL (base64), use it directly
          if (practice.branding.logo.startsWith('data:image')) {
            const logoWidth = 40;
            const logoHeight = 30;
            pdf.addImage(practice.branding.logo, 'JPEG', pageWidth - rightMargin - logoWidth, yPosition, logoWidth, logoHeight);
            return logoHeight + 5;
          }
          // If logo is a URL, we'd need to fetch it (more complex in browser environment)
          // For now, we'll show a placeholder
          return 0;
        } catch (error) {
          console.warn('Could not load logo:', error);
          return 0;
        }
      }
      return 0;
    };

    // Helper function to add page numbers (starting from page 2)
    const addPageNumber = () => {
      if (currentPage > 1) {
        pdf.setFontSize(10);
        pdf.setFont('helvetica', 'normal');
        pdf.setTextColor(100, 100, 100);
        pdf.text(`Page ${currentPage}`, pageWidth - rightMargin, pageHeight - 15, { align: 'right' });
      }
    };

    // Helper function to add header with logo on each page
    const addPageHeader = () => {
      if (currentPage > 1) {
        // Add logo on subsequent pages
        addLogo();
        
        // Add practice name in smaller font
        pdf.setFontSize(12);
        pdf.setFont('helvetica', 'bold');
        pdf.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
        pdf.text(practice.name || 'DENTAL PRACTICE', leftMargin, topMargin + 10);
        
        // Add a line separator
        pdf.setDrawColor(200, 200, 200);
        pdf.setLineWidth(0.5);
        pdf.line(leftMargin, topMargin + 20, pageWidth - rightMargin, topMargin + 20);
        
        yPosition = topMargin + 30;
      }
    };

    // Helper function to check for page break and add new page
    const checkPageBreak = (neededSpace) => {
      if (yPosition + neededSpace > pageHeight - bottomMargin) {
        addPageNumber();
        pdf.addPage();
        currentPage++;
        addPageHeader();
        return true;
      }
      return false;
    };

    // Helper function to check if section header needs page break (prevent orphan headers)
    const checkSectionPageBreak = (headerHeight = 25, minContentSpace = 30) => {
      const totalNeeded = headerHeight + minContentSpace;
      if (yPosition + totalNeeded > pageHeight - bottomMargin) {
        addPageNumber();
        pdf.addPage();
        currentPage++;
        addPageHeader();
        return true;
      }
      return false;
    };

    // Helper function to add standardized text
    const addText = (text, fontSize = 11, style = 'normal', color = [60, 60, 60], spacing = 5) => {
      pdf.setFontSize(fontSize);
      pdf.setFont('helvetica', style);
      pdf.setTextColor(color[0], color[1], color[2]);

      const lines = pdf.splitTextToSize(text, contentWidth);
      const lineHeight = fontSize * 0.4;
      const totalHeight = lines.length * lineHeight + spacing;
      
      checkPageBreak(totalHeight);
      
      pdf.text(lines, leftMargin, yPosition);
      yPosition += totalHeight;
      
      return yPosition;
    };

    // Helper function to add section header
    const addSectionHeader = (title, addSpaceBefore = true) => {
      if (addSpaceBefore) yPosition += 8;
      
      // Check if header would be orphaned (prevent header alone at bottom of page)
      checkSectionPageBreak(25, 35);
      
      // Header line
      pdf.setDrawColor(primaryColor[0], primaryColor[1], primaryColor[2]);
      pdf.setLineWidth(1);
      pdf.line(leftMargin, yPosition, pageWidth - rightMargin, yPosition);
      yPosition += 5;
      
      // Header text
      pdf.setFontSize(12);
      pdf.setFont('helvetica', 'bold');
      pdf.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
      pdf.text(title.toUpperCase(), leftMargin, yPosition);
      yPosition += 15;
    };

    // Helper function to add bullet points
    const addBulletList = (items, indent = 0) => {
      if (!items || items.length === 0) return;
      
      // Estimate space needed for bullet list to keep it together
      const estimatedHeight = items.length * 15; // rough estimate
      if (estimatedHeight > 50) {
        // For long lists, just check normal page break
        items.forEach((item) => {
          const bulletX = leftMargin + indent;
          const textX = bulletX + 10;
          const textWidth = contentWidth - indent - 10;
          
          const lines = pdf.splitTextToSize(item, textWidth);
          const itemHeight = lines.length * 4.4 + 2;
          checkPageBreak(itemHeight);
          
          pdf.setFontSize(11);
          pdf.setFont('helvetica', 'normal');
          pdf.setTextColor(60, 60, 60);
          pdf.text('•', bulletX, yPosition);
          pdf.text(lines, textX, yPosition);
          yPosition += itemHeight;
        });
      } else {
        // For shorter lists, try to keep together
        checkPageBreak(estimatedHeight);
        
        items.forEach((item) => {
          const bulletX = leftMargin + indent;
          const textX = bulletX + 10;
          const textWidth = contentWidth - indent - 10;
          
          const lines = pdf.splitTextToSize(item, textWidth);
          const itemHeight = lines.length * 4.4 + 2;
          
          pdf.setFontSize(11);
          pdf.setFont('helvetica', 'normal');
          pdf.setTextColor(60, 60, 60);
          pdf.text('•', bulletX, yPosition);
          pdf.text(lines, textX, yPosition);
          yPosition += itemHeight;
        });
      }
    };

    // Helper function to add info box
    const addInfoBox = (title, content, isEmergency = false) => {
      const boxPadding = 10;
      const titleHeight = 15;
      const contentLines = pdf.splitTextToSize(content, contentWidth - (boxPadding * 2));
      const contentHeight = contentLines.length * 4.4;
      const totalBoxHeight = titleHeight + contentHeight + (boxPadding * 2);
      
      // Ensure info box stays together on same page
      checkPageBreak(totalBoxHeight);
      
      // Box background
      if (isEmergency) {
        pdf.setFillColor(254, 242, 242);
        pdf.setDrawColor(239, 68, 68);
      } else {
        pdf.setFillColor(248, 250, 252);
        pdf.setDrawColor(203, 213, 225);
      }
      
      pdf.setLineWidth(1);
      pdf.rect(leftMargin, yPosition, contentWidth, totalBoxHeight, 'FD');
      
      // Title
      pdf.setFontSize(11);
      pdf.setFont('helvetica', 'bold');
      if (isEmergency) {
        pdf.setTextColor(185, 28, 28);
      } else {
        pdf.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
      }
      pdf.text(title, leftMargin + boxPadding, yPosition + titleHeight);
      
      // Content
      pdf.setFontSize(10);
      pdf.setFont('helvetica', 'normal');
      pdf.setTextColor(60, 60, 60);
      pdf.text(contentLines, leftMargin + boxPadding, yPosition + titleHeight + 8);
      
      yPosition += totalBoxHeight + 10;
    };

    // START DOCUMENT CREATION

    // Header - Practice Information with Logo
    const logoHeight = await addLogo();
    
    pdf.setFontSize(20);
    pdf.setFont('helvetica', 'bold');
    pdf.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
    pdf.text(practice.name || 'DENTAL PRACTICE', leftMargin, yPosition);
    yPosition += 25;

    // Practice contact information
    pdf.setFontSize(11);
    pdf.setFont('helvetica', 'normal');
    pdf.setTextColor(80, 80, 80);
    
    let contactInfo = [];
    if (practice.phone) contactInfo.push(`Phone: ${practice.phone}`);
    if (practice.email) contactInfo.push(`Email: ${practice.email}`);
    if (practice.website) contactInfo.push(`Website: ${practice.website}`);
    
    if (contactInfo.length > 0) {
      pdf.text(contactInfo.join(' | '), leftMargin, yPosition);
      yPosition += 12;
    }

    if (practice.address) {
      const addr = practice.address;
      const addressText = `${addr.street}, ${addr.city}, ${addr.state} ${addr.zipCode}`;
      pdf.text(addressText, leftMargin, yPosition);
      yPosition += 20;
    } else {
      yPosition += 8;
    }

    // Document title
    pdf.setFontSize(16);
    pdf.setFont('helvetica', 'bold');
    pdf.setTextColor(0, 0, 0);
    pdf.text('POST-OPERATIVE CARE INSTRUCTIONS', pageWidth / 2, yPosition, { align: 'center' });
    yPosition += 25;

    // Patient Information
    addSectionHeader('PATIENT INFORMATION', false);
    
    const patientInfo = [
      `Patient Name: ${patient.firstName} ${patient.lastName}`,
      `Email: ${patient.email}`,
      assignment.performedDate ? `Procedure Date: ${new Date(assignment.performedDate).toLocaleDateString('en-US', { 
        year: 'numeric', month: 'long', day: 'numeric' 
      })}` : null,
      assignment.dentistName ? `Treating Dentist: ${assignment.dentistName}` : null,
      assignment.followUpDate ? `Follow-up Date: ${new Date(assignment.followUpDate).toLocaleDateString('en-US', { 
        year: 'numeric', month: 'long', day: 'numeric' 
      })}` : null
    ].filter(info => info);

    patientInfo.forEach(info => {
      addText(info, 11, 'normal', [60, 60, 60], 4);
    });

    yPosition += 5;

    // Procedure Information
    addSectionHeader('PROCEDURE PERFORMED');
    addText(`Procedure: ${assignment.procedureName || procedure.name}`, 12, 'bold', [0, 0, 0]);
    if (procedure.specialtyName) {
      addText(`Specialty: ${procedure.specialtyName}`, 11, 'normal', [80, 80, 80]);
    }

    // Custom practice message
    if (practice.branding?.welcomeMessage) {
      yPosition += 10;
      addInfoBox('MESSAGE FROM YOUR DENTAL TEAM', practice.branding.welcomeMessage);
    }

    // Custom practice notes
    if (assignment.practiceNotes) {
      addSectionHeader('SPECIAL INSTRUCTIONS FROM YOUR DENTIST');
      addText(assignment.practiceNotes, 11, 'normal', [60, 60, 60]);
    }

    // Custom instructions
    if (assignment.customInstructions && assignment.customInstructions.length > 0) {
      addSectionHeader('ADDITIONAL CARE INSTRUCTIONS');
      addBulletList(assignment.customInstructions);
    }

    // Emergency notice
    yPosition += 15;
    addInfoBox('EMERGENCY NOTICE', 
      'If you experience severe bleeding that does not stop, difficulty breathing, severe swelling, signs of severe allergic reaction, or any symptoms that cause you serious concern, call 911 immediately. For urgent dental concerns during office hours, contact our office. For after-hours emergencies, follow the emergency contact instructions provided by your dentist.',
      true
    );

    // Procedure sections
    if (procedure.overview) {
      addSectionHeader('PROCEDURE OVERVIEW');
      addText(procedure.overview, 11, 'normal', [60, 60, 60]);
    }

    if (procedure.immediateAftercare) {
      addSectionHeader('IMMEDIATE AFTERCARE INSTRUCTIONS (First 24 Hours)');
      addBulletList(procedure.immediateAftercare);
    }

    if (procedure.dietRestrictions) {
      addSectionHeader('DIETARY GUIDELINES');
      addBulletList(procedure.dietRestrictions);
    }

    if (procedure.warningSignsToCallDoctor) {
      addSectionHeader('WARNING SIGNS - CONTACT OUR OFFICE IMMEDIATELY');
      addText('Contact our office immediately if you experience any of the following:', 11, 'bold', [185, 28, 28]);
      yPosition += 5;
      addBulletList(procedure.warningSignsToCallDoctor);
    }

    // Recovery timeline
    if (procedure.recoveryTimeline && procedure.recoveryTimeline.length > 0) {
      addSectionHeader('RECOVERY TIMELINE');
      
      procedure.recoveryTimeline.forEach((timeline) => {
        checkPageBreak(20);
        
        // Day header
        pdf.setFontSize(11);
        pdf.setFont('helvetica', 'bold');
        pdf.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
        pdf.text(`Day ${timeline.day}:`, leftMargin, yPosition);
        
        // Activity description
        pdf.setFont('helvetica', 'normal');
        pdf.setTextColor(60, 60, 60);
        const activityLines = pdf.splitTextToSize(timeline.activity, contentWidth - 50);
        pdf.text(activityLines, leftMargin + 50, yPosition);
        
        yPosition += Math.max(15, activityLines.length * 4.4 + 5);
      });
    }

    if (procedure.medications) {
      addSectionHeader('MEDICATION INSTRUCTIONS');
      addBulletList(procedure.medications);
    }

    // Contact information
    addSectionHeader('CONTACT INFORMATION');
    addText('For questions or concerns regarding your post-operative care:', 11, 'bold', [60, 60, 60]);
    yPosition += 5;
    
    const contactDetails = [
      practice.name || 'Dental Practice',
      practice.phone ? `Phone: ${practice.phone}` : null,
      practice.email ? `Email: ${practice.email}` : null
    ].filter(detail => detail);

    contactDetails.forEach(detail => {
      addText(detail, 11, 'normal', [60, 60, 60], 4);
    });

    // Office hours note
    yPosition += 10;
    addText('Please contact our office during regular business hours for non-emergency questions. Follow your dentist\'s after-hours emergency contact instructions for urgent concerns outside of office hours.', 10, 'italic', [100, 100, 100]);

    // Add final page number
    addPageNumber();

    // Footer on last page
    yPosition = pageHeight - 30;
    pdf.setFontSize(8);
    pdf.setFont('helvetica', 'normal');
    pdf.setTextColor(120, 120, 120);
    pdf.text('Generated by DentalRescueBot | www.theoncallbot.com', leftMargin, yPosition);
    pdf.text(`Generated on ${new Date().toLocaleDateString('en-US')} at ${new Date().toLocaleTimeString('en-US')}`, 
             pageWidth - rightMargin, yPosition, { align: 'right' });
    
    pdf.text('© 2025 The OnCall Bot LLC. Follow your dentist\'s specific instructions.', 
             pageWidth / 2, yPosition + 8, { align: 'center' });

    // Professional file naming
    const fileName = `PostOp_${patient.lastName}_${patient.firstName}_${new Date().getFullYear()}${String(new Date().getMonth() + 1).padStart(2, '0')}${String(new Date().getDate()).padStart(2, '0')}.pdf`;
    pdf.save(fileName);
    
    return true;
  } catch (error) {
    console.error('Error generating branded PDF:', error);
    return false;
  }
};